SRM_UNDELETABLES=(
    "$HOME"
    "$HOME/downloads"
    "$HOME/documents"
    "$HOME/images"
    "$HOME/dev"
    "$HOME/.config"
    "$HOME/.dotconfig"
    "$HOME/Videos"
    "${XDG_HOME_BIN}"
    "$HOME/.local"
    "$HOME/UNDELTEST"
)
